import { Router } from "express";
import { requireAuth } from "../../middleware/auth";
import { authRouter } from "./auth";
import { dashboardRouter } from "./dashboard";
import { categoriesRouter } from "./categories";
import { questionsRouter } from "./questions";
import { faqsRouter } from "./faqs";
import { articlesRouter } from "./articles";
import { settingsRouter } from "./settings";
import { reportsRouter } from "./reports";
import { contributionsRouter } from "./contributions";
import { categoryRequestsRouter } from "./categoryRequests";
import { notificationsRouter } from "./notifications";
import { auditRouter } from "./audit";
import { whatsappRouter } from "./whatsapp";
import { sessionsRouter } from "./sessions";
import { uploadsRouter } from "./uploads";
import { contactRouter } from "./contact";
import { adminsRouter } from "./admins";
import { monetizationAdminRouter } from "./monetization";
import { analyticsRouter } from "./analytics";
import { revenueRouter } from "./revenue";
import { healthRouter } from "./health";
import { jobsRouter } from "./jobs";

export const adminRouter = Router();

adminRouter.use("/auth", authRouter);
adminRouter.use(requireAuth);

adminRouter.use("/health", healthRouter);
adminRouter.use("/jobs", jobsRouter);
adminRouter.use("/dashboard", dashboardRouter);
adminRouter.use("/categories", categoriesRouter);
adminRouter.use("/questions", questionsRouter);
adminRouter.use("/faqs", faqsRouter);
adminRouter.use("/articles", articlesRouter);
adminRouter.use("/settings", settingsRouter);
adminRouter.use("/reports", reportsRouter);
adminRouter.use("/contributions", contributionsRouter);
adminRouter.use("/category-requests", categoryRequestsRouter);
adminRouter.use("/notifications", notificationsRouter);
adminRouter.use("/audit", auditRouter);
adminRouter.use("/whatsapp", whatsappRouter);
adminRouter.use("/sessions", sessionsRouter);
adminRouter.use("/uploads", uploadsRouter);
adminRouter.use("/contact", contactRouter);
adminRouter.use("/admins", adminsRouter);
adminRouter.use("/monetization", monetizationAdminRouter);
adminRouter.use("/analytics", analyticsRouter);
adminRouter.use("/revenue", revenueRouter);
